#!/bin/sh
set -eu

FORCE_OVERWRITE=false
if [ "${1:-}" = "--force" ]; then
    FORCE_OVERWRITE=true
fi

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOURCE_DIR="$SCRIPT_DIR"
DEST_DIR="$HOME/.hammerspoon"
DEST_MODULE_DIR="$DEST_DIR/clickthrough"
DEST_INIT="$DEST_DIR/init.lua"
BACKUP_FILE="$DEST_DIR/init_backup.lua"

if [ ! -d "$SOURCE_DIR/clickthrough" ]; then
    echo "Source module directory not found: $SOURCE_DIR/clickthrough" >&2
    exit 1
fi

mkdir -p "$DEST_MODULE_DIR"

cp -R "$SOURCE_DIR/clickthrough/." "$DEST_MODULE_DIR/"

echo "Installed clickthrough module files to $DEST_MODULE_DIR"

if [ -f "$DEST_INIT" ]; then
    if [ "$FORCE_OVERWRITE" = true ] || ! grep -q 'require("clickthrough")' "$DEST_INIT" && ! grep -q "require('clickthrough')" "$DEST_INIT"; then
        cp "$DEST_INIT" "$BACKUP_FILE"
        echo "Backed up existing config to $BACKUP_FILE"
    fi

    if grep -q 'require("clickthrough")' "$DEST_INIT" || grep -q "require('clickthrough')" "$DEST_INIT"; then
        echo "Existing ~/.hammerspoon/init.lua already loads clickthrough."
    else
        printf '\n-- Load Apple Click-Through module\npcall(function() require("clickthrough") end)\n' >> "$DEST_INIT"
        echo "Appended require(\"clickthrough\") to existing init.lua"
    fi
else
    cat > "$DEST_INIT" <<'EOF'
-- ~/.hammerspoon/init.lua
-- Auto-generated by apple-click-through/install.sh
pcall(function() require("clickthrough") end)
EOF
    echo "Created new Hammerspoon config at $DEST_INIT"
fi

echo "Installation complete. Reload Hammerspoon config."
